import { buildTree } from "../builder.js";

export const domainKnowledgeTree = buildTree("domain-knowledge", "Domain Knowledge", [
  // ── Sectors (Organization Type) ──────────────────────────────
  {
    id: "sector",
    label: "Organization Sector",
    children: [
      {
        id: "federal",
        label: "Federal Government",
        aliases: ["federal", "fed", "us government", "federal agency", "federal contract"],
        children: [
          { id: "dod", label: "Department of Defense", aliases: ["dod", "military", "defense", "army", "navy", "air force", "marines", "pentagon", "defense contractor"] },
          { id: "dhs", label: "Department of Homeland Security", aliases: ["dhs", "homeland security", "tsa", "fema", "ice", "cbp", "secret service"] },
          { id: "hhs", label: "Health & Human Services", aliases: ["hhs", "cms", "cdc", "nih", "fda", "samhsa", "acf"] },
          { id: "va", label: "Veterans Affairs", aliases: ["va", "veterans", "veterans administration", "va hospital"] },
          { id: "doi", label: "Department of Interior", aliases: ["doi", "interior", "blm", "nps", "national park service"] },
          { id: "doe", label: "Department of Energy", aliases: ["doe", "energy department", "national lab"] },
          { id: "usda", label: "USDA", aliases: ["usda", "agriculture", "department of agriculture", "forest service"] },
          { id: "doj", label: "Department of Justice", aliases: ["doj", "justice department", "fbi", "dea", "atf", "us marshals"] },
          { id: "dot", label: "Department of Transportation", aliases: ["dot", "faa", "fhwa", "nhtsa", "fra"] },
          { id: "ed", label: "Department of Education", aliases: ["dept of education", "federal education", "ed.gov"] },
          { id: "gsa", label: "GSA", aliases: ["gsa", "general services administration"] },
          { id: "sba", label: "Small Business Administration", aliases: ["sba"] },
          { id: "ssa", label: "Social Security Administration", aliases: ["ssa", "social security"] },
          { id: "irs", label: "IRS / Treasury", aliases: ["irs", "treasury", "internal revenue"] },
          { id: "epa", label: "EPA", aliases: ["epa", "environmental protection"] },
          { id: "nasa", label: "NASA", aliases: ["nasa", "space agency"] },
          { id: "intel", label: "Intelligence Community", aliases: ["intelligence", "cia", "nsa", "dia", "nro", "ngi", "ic"] },
        ],
      },
      {
        id: "state",
        label: "State Government",
        aliases: ["state government", "state agency", "state contract", "state of"],
        children: [
          { id: "state-it", label: "State IT / CIO", aliases: ["state cio", "state it", "state technology", "doits", "doit"] },
          { id: "state-hhs", label: "State Health & Human Services", aliases: ["state hhs", "dcfs", "dcf", "dhs", "state health", "child welfare", "child protective services", "cps", "tanf", "snap", "medicaid state", "state medicaid"] },
          { id: "state-dol", label: "State Labor / Workforce", aliases: ["state labor", "unemployment", "workforce development", "ides", "des"] },
          { id: "state-dot", label: "State Transportation", aliases: ["state dot", "state transportation", "dmv", "idot"] },
          { id: "state-corrections", label: "State Corrections", aliases: ["corrections", "state prison", "doc", "department of corrections", "idoc"] },
          { id: "state-revenue", label: "State Revenue / Tax", aliases: ["state tax", "state revenue", "department of revenue", "idor"] },
          { id: "state-education", label: "State Education Agency", aliases: ["state education", "isbe", "doe state", "state board of education"] },
          { id: "state-police", label: "State Law Enforcement", aliases: ["state police", "state patrol", "isp"] },
          { id: "state-env", label: "State Environmental", aliases: ["state environmental", "state epa", "iepa"] },
          { id: "state-courts", label: "State Courts / Judiciary", aliases: ["state courts", "judiciary", "circuit court", "state supreme court"] },
        ],
      },
      {
        id: "local",
        label: "Local / Municipal Government",
        aliases: ["local government", "municipal", "county", "city government", "township"],
        children: [
          { id: "city-it", label: "Municipal IT", aliases: ["city it", "city technology", "municipal technology"] },
          { id: "county-gov", label: "County Government", aliases: ["county", "county government", "county board", "cook county", "county clerk"] },
          { id: "public-safety", label: "Public Safety / 911", aliases: ["public safety", "911", "dispatch", "emergency services", "ems"] },
          { id: "utilities", label: "Public Utilities", aliases: ["public utilities", "water department", "sanitation", "public works"] },
          { id: "transit", label: "Public Transit", aliases: ["transit", "public transit", "cta", "metra", "pace", "bus authority", "transit authority"] },
          { id: "parks", label: "Parks & Recreation", aliases: ["parks", "recreation", "park district", "forest preserve"] },
        ],
      },
      {
        id: "commercial",
        label: "Commercial / Private Sector",
        aliases: ["commercial", "private sector", "corporate", "private company", "enterprise"],
        children: [
          { id: "startup", label: "Startup", aliases: ["startup", "start-up", "early stage", "series a", "series b", "seed stage"] },
          { id: "smb", label: "Small/Medium Business", aliases: ["smb", "small business", "medium business", "mid-market"] },
          { id: "enterprise-corp", label: "Large Enterprise", aliases: ["enterprise", "fortune 500", "fortune 100", "large corporation", "global corporation", "multinational"] },
          { id: "consulting", label: "Consulting / Professional Services", aliases: ["consulting", "professional services", "advisory", "management consulting", "deloitte", "accenture", "mckinsey", "booz allen", "kpmg", "ey", "pwc"] },
          { id: "systems-integrator", label: "Systems Integrator", aliases: ["systems integrator", "si", "integration partner", "ibm", "infosys", "wipro", "tcs", "cognizant", "hcl", "tech mahindra", "capgemini"] },
          { id: "staffing", label: "Staffing / Recruiting", aliases: ["staffing", "recruiting", "staffing agency", "recruitment", "talent acquisition", "headhunter"] },
          { id: "product-company", label: "Product Company", aliases: ["product company", "saas", "software product", "platform company"] },
        ],
      },
      {
        id: "nonprofit",
        label: "Nonprofit / NGO",
        aliases: ["nonprofit", "non-profit", "ngo", "501c3", "501(c)(3)", "charitable", "not-for-profit", "foundation"],
        children: [
          { id: "social-services", label: "Social Services Nonprofit", aliases: ["social services", "human services", "community services", "united way", "salvation army", "ymca", "ywca"] },
          { id: "healthcare-nonprofit", label: "Healthcare Nonprofit", aliases: ["healthcare nonprofit", "hospital nonprofit", "community health", "fqhc", "free clinic"] },
          { id: "advocacy", label: "Advocacy / Policy", aliases: ["advocacy", "policy", "think tank", "lobbying", "public interest"] },
          { id: "international-dev", label: "International Development", aliases: ["international development", "usaid", "world bank", "un", "unicef", "undp", "international aid"] },
          { id: "arts-culture", label: "Arts & Culture", aliases: ["arts", "culture", "museum", "gallery", "performing arts", "symphony", "theater"] },
          { id: "environmental-npo", label: "Environmental Nonprofit", aliases: ["environmental nonprofit", "conservation", "wildlife", "nature conservancy", "sierra club"] },
          { id: "religious", label: "Faith-Based Organization", aliases: ["faith-based", "religious", "church", "temple", "mosque", "ministry"] },
        ],
      },
      {
        id: "education",
        label: "Education Sector",
        aliases: ["education sector", "academic", "academia"],
        children: [
          { id: "k12", label: "K-12 Education", aliases: ["k-12", "k12", "public school", "school district", "elementary school", "middle school", "high school", "cps", "chicago public schools"] },
          { id: "charter", label: "Charter / Private School", aliases: ["charter school", "private school", "independent school", "magnet school", "parochial school"] },
          { id: "community-college", label: "Community College", aliases: ["community college", "junior college", "two-year college", "city colleges"] },
          { id: "university", label: "University / 4-Year", aliases: ["university", "college", "four-year", "higher education", "higher ed", "state university", "research university"] },
          { id: "for-profit-edu", label: "For-Profit Education", aliases: ["for-profit education", "for-profit college", "online university", "trade school", "vocational school"] },
          { id: "edtech", label: "EdTech", aliases: ["edtech", "education technology", "learning platform", "lms", "courseware"] },
        ],
      },
      {
        id: "healthcare-sector",
        label: "Healthcare Sector",
        aliases: ["healthcare sector", "health sector"],
        children: [
          { id: "hospital-system", label: "Hospital / Health System", aliases: ["hospital", "health system", "medical center", "hospital system", "academic medical center"] },
          { id: "outpatient", label: "Outpatient / Ambulatory", aliases: ["outpatient", "ambulatory", "clinic", "urgent care", "physicians group", "medical group"] },
          { id: "long-term-care", label: "Long-Term Care / SNF", aliases: ["long-term care", "nursing home", "snf", "skilled nursing", "assisted living", "memory care", "rehabilitation center"] },
          { id: "home-health", label: "Home Health / Hospice", aliases: ["home health", "home care", "hospice", "visiting nurse", "home health aide"] },
          { id: "behavioral-health", label: "Behavioral Health", aliases: ["behavioral health", "mental health", "substance abuse", "addiction", "psychiatric", "counseling center"] },
          { id: "health-insurance", label: "Health Insurance / Payer", aliases: ["health insurance", "payer", "managed care", "hmo", "ppo", "medicare advantage", "blue cross", "bcbs", "cigna", "aetna", "unitedhealth"] },
          { id: "pharma", label: "Pharmaceutical / Biotech", aliases: ["pharmaceutical", "pharma", "biotech", "clinical trials", "drug development", "fda approval"] },
          { id: "medical-device", label: "Medical Device", aliases: ["medical device", "medtech", "medical equipment", "diagnostic equipment"] },
        ],
      },
    ],
  },
  // ── Industry Verticals ───────────────────────────────────────
  {
    id: "industry",
    label: "Industry Verticals",
    children: [
      {
        id: "finance",
        label: "Financial Services",
        children: [
          { id: "banking", label: "Banking", aliases: ["banking", "core banking", "retail banking", "commercial banking", "investment banking"] },
          { id: "trading", label: "Trading / Capital Markets", aliases: ["trading", "capital markets", "algorithmic trading", "hft", "equities", "fixed income", "derivatives"] },
          { id: "payments", label: "Payments / Fintech", aliases: ["payments", "fintech", "payment processing", "payment gateway", "stripe", "square"] },
          { id: "insurance-industry", label: "Insurance", aliases: ["insurance", "claims", "underwriting", "actuarial", "reinsurance", "insurtech"] },
          { id: "wealth-mgmt", label: "Wealth Management", aliases: ["wealth management", "asset management", "portfolio management", "investment advisory"] },
        ],
      },
      {
        id: "energy",
        label: "Energy & Utilities",
        children: [
          { id: "oil-gas", label: "Oil & Gas", aliases: ["oil", "gas", "petroleum", "upstream", "downstream", "midstream", "refinery"] },
          { id: "renewables", label: "Renewable Energy", aliases: ["renewable", "solar", "wind", "clean energy", "green energy"] },
          { id: "electric-utility", label: "Electric Utility", aliases: ["electric utility", "power generation", "grid", "transmission", "distribution"] },
        ],
      },
      {
        id: "manufacturing",
        label: "Manufacturing",
        aliases: ["manufacturing", "industrial", "factory", "production"],
        children: [
          { id: "discrete-mfg", label: "Discrete Manufacturing", aliases: ["discrete manufacturing", "assembly", "automotive manufacturing", "aerospace manufacturing"] },
          { id: "process-mfg", label: "Process Manufacturing", aliases: ["process manufacturing", "chemical", "food manufacturing", "beverage"] },
        ],
      },
      {
        id: "telecom",
        label: "Telecommunications",
        aliases: ["telecom", "telecommunications", "telco", "wireless", "broadband", "isp"],
      },
      {
        id: "retail",
        label: "Retail & E-Commerce",
        aliases: ["retail", "e-commerce", "ecommerce", "online retail", "marketplace", "omnichannel"],
      },
      {
        id: "logistics",
        label: "Logistics & Supply Chain",
        aliases: ["logistics company", "supply chain management", "freight management", "shipping company", "3pl", "distribution center"],
      },
      {
        id: "media",
        label: "Media & Entertainment",
        aliases: ["media company", "entertainment industry", "publishing house", "broadcasting company", "streaming service", "gaming company", "adtech company"],
      },
      {
        id: "real-estate",
        label: "Real Estate / PropTech",
        aliases: ["real estate company", "proptech", "property management company", "commercial real estate", "reit"],
      },
      {
        id: "agriculture",
        label: "Agriculture / AgTech",
        aliases: ["agriculture industry", "agtech", "farming industry", "agribusiness"],
      },
      {
        id: "legal",
        label: "Legal / LegalTech",
        aliases: ["law firm", "legaltech", "legal services firm", "legal department", "litigation support"],
      },
      {
        id: "construction",
        label: "Construction / AEC",
        aliases: ["construction company", "construction industry", "aec firm", "general contractor", "construction management"],
      },
    ],
  },
  // ── Compliance & Regulatory Frameworks ───────────────────────
  {
    id: "compliance",
    label: "Compliance & Regulatory",
    children: [
      { id: "hipaa", label: "HIPAA", aliases: ["hipaa", "phi", "protected health information", "health privacy"] },
      { id: "fedramp", label: "FedRAMP", aliases: ["fedramp", "federal risk", "fedramp high", "fedramp moderate"] },
      { id: "fisma", label: "FISMA / NIST", aliases: ["fisma", "nist", "nist 800-53", "nist cybersecurity framework", "nist csf"] },
      { id: "cmmc", label: "CMMC", aliases: ["cmmc", "cybersecurity maturity model", "dfars"] },
      { id: "itar", label: "ITAR / EAR", aliases: ["itar", "ear", "export control", "international traffic in arms"] },
      { id: "pci-dss", label: "PCI-DSS", aliases: ["pci", "pci-dss", "payment card industry", "cardholder data"] },
      { id: "sox", label: "SOX", aliases: ["sox", "sarbanes-oxley", "section 404"] },
      { id: "gdpr", label: "GDPR", aliases: ["gdpr", "general data protection", "data privacy", "eu data protection"] },
      { id: "ferpa", label: "FERPA", aliases: ["ferpa", "student records", "education records privacy"] },
      { id: "cjis", label: "CJIS", aliases: ["cjis", "criminal justice information", "fbi cjis"] },
      { id: "stateramp", label: "StateRAMP", aliases: ["stateramp", "state risk"] },
      { id: "section-508", label: "Section 508 / ADA", aliases: ["section 508", "508 compliance", "ada compliance", "accessibility", "wcag", "a11y"] },
      { id: "fips", label: "FIPS", aliases: ["fips", "fips 140", "fips 140-2", "fips 199", "federal information processing"] },
      { id: "il4-il5", label: "Impact Level 4/5", aliases: ["il4", "il5", "impact level 4", "impact level 5", "dod cloud", "govcloud"] },
    ],
  },
  // ── Procurement & Contracting ────────────────────────────────
  {
    id: "procurement",
    label: "Government Procurement",
    children: [
      { id: "rfp-process", label: "RFP/RFQ Process", aliases: ["rfp", "rfq", "rfi", "request for proposal", "request for quote", "bid", "proposal writing"] },
      { id: "gsa-schedule", label: "GSA Schedule", aliases: ["gsa schedule", "gsa contract", "mas", "multiple award schedule", "8a stars"] },
      { id: "gwac", label: "GWAC", aliases: ["gwac", "government-wide acquisition", "alliant", "cio-sp3", "vets 2"] },
      { id: "state-master", label: "State Master Contract", aliases: ["state master contract", "state contract", "blanket purchase", "bpa"] },
      { id: "tops", label: "TOPS Contract", aliases: ["tops", "technology outsourcing", "cms tops"] },
      { id: "idiq", label: "IDIQ", aliases: ["idiq", "indefinite delivery", "task order"] },
      { id: "sam-gov", label: "SAM.gov Registration", aliases: ["sam", "sam.gov", "system for award management", "cage code", "duns"] },
      { id: "set-aside", label: "Set-Aside Programs", aliases: ["set-aside", "8a", "hubzone", "sdvosb", "wosb", "dbe", "mbe", "disadvantaged business"] },
      { id: "security-clearance", label: "Security Clearance", aliases: ["security clearance", "secret", "top secret", "ts/sci", "public trust", "naci", "bi", "ssbi"] },
    ],
  },
  // ── Healthcare-Specific Knowledge ────────────────────────────
  {
    id: "healthcare",
    label: "Healthcare Domain",
    children: [
      { id: "ehr", label: "Electronic Health Records", aliases: ["ehr", "emr", "epic", "cerner", "meditech", "allscripts", "athenahealth", "nextgen", "eclinicalworks"] },
      { id: "clinical-workflows", label: "Clinical Workflows", aliases: ["clinical workflows", "clinical operations", "patient flow", "care coordination", "care management"] },
      { id: "medical-coding", label: "Medical Coding / Billing", aliases: ["medical coding", "icd-10", "cpt codes", "medical billing", "revenue cycle", "rcm", "hcpcs", "drg"] },
      { id: "telehealth", label: "Telehealth", aliases: ["telehealth", "telemedicine", "remote health", "virtual visit", "remote patient monitoring"] },
      { id: "clinical-research", label: "Clinical Research / Trials", aliases: ["clinical research", "clinical trials", "irb", "clinical study", "research protocol"] },
      { id: "population-health", label: "Population Health", aliases: ["population health", "public health", "epidemiology", "health outcomes", "social determinants", "sdoh"] },
      { id: "health-it", label: "Health IT Standards", aliases: ["health it", "hl7", "fhir", "dicom", "x12", "edi 837", "edi 835", "cda", "ccda", "interoperability"] },
    ],
  },
]);
