import { buildTree } from "../builder.js";

export const technologyTree = buildTree("technology", "Technology", [
  {
    id: "languages",
    label: "Programming Languages",
    children: [
      { id: "python", label: "Python", aliases: ["py", "python3", "cpython"] },
      { id: "javascript", label: "JavaScript", aliases: ["js", "ecmascript", "es6", "es2015"] },
      { id: "typescript", label: "TypeScript", aliases: ["ts"], related: ["languages.javascript"] },
      { id: "java", label: "Java", aliases: ["jdk", "jvm"] },
      { id: "csharp", label: "C#", aliases: ["c#", "c-sharp", "dotnet", ".net"] },
      { id: "go", label: "Go", aliases: ["golang"] },
      { id: "rust", label: "Rust", aliases: ["rustlang"] },
      { id: "ruby", label: "Ruby", aliases: ["rb"] },
      { id: "php", label: "PHP" },
      { id: "swift", label: "Swift" },
      { id: "kotlin", label: "Kotlin", aliases: ["kt"], related: ["languages.java"] },
      { id: "scala", label: "Scala", related: ["languages.java"] },
      { id: "r", label: "R", aliases: ["r-lang", "rlang"] },
      { id: "sql", label: "SQL", aliases: ["structured query language"] },
      { id: "cpp", label: "C++", aliases: ["c++", "cplusplus"] },
      { id: "c", label: "C", aliases: ["clang", "ansi-c"] },
      { id: "shell", label: "Shell/Bash", aliases: ["bash", "sh", "zsh", "shell scripting"] },
      { id: "powershell", label: "PowerShell", aliases: ["pwsh", "ps1"] },
    ],
  },
  {
    id: "frontend",
    label: "Frontend Frameworks",
    children: [
      { id: "react", label: "React", aliases: ["reactjs", "react.js"], related: ["languages.javascript", "languages.typescript"] },
      { id: "angular", label: "Angular", aliases: ["angularjs", "angular.js", "ng"], related: ["languages.typescript"] },
      { id: "vue", label: "Vue.js", aliases: ["vuejs", "vue"], related: ["languages.javascript"] },
      { id: "nextjs", label: "Next.js", aliases: ["next", "nextjs"], related: ["frontend.react"] },
      { id: "svelte", label: "Svelte", aliases: ["sveltekit"] },
      { id: "html", label: "HTML", aliases: ["html5"] },
      { id: "css", label: "CSS", aliases: ["css3", "cascading style sheets"] },
      { id: "tailwind", label: "Tailwind CSS", aliases: ["tailwindcss"], related: ["frontend.css"] },
      { id: "bootstrap", label: "Bootstrap", related: ["frontend.css"] },
      { id: "sass", label: "Sass/SCSS", aliases: ["scss", "sass"], related: ["frontend.css"] },
    ],
  },
  {
    id: "backend",
    label: "Backend Frameworks",
    children: [
      { id: "nodejs", label: "Node.js", aliases: ["node", "node.js"], related: ["languages.javascript"] },
      { id: "express", label: "Express.js", aliases: ["expressjs"], related: ["backend.nodejs"] },
      { id: "fastapi", label: "FastAPI", related: ["languages.python"] },
      { id: "django", label: "Django", related: ["languages.python"] },
      { id: "flask", label: "Flask", related: ["languages.python"] },
      { id: "spring", label: "Spring Boot", aliases: ["spring", "spring-boot", "springboot"], related: ["languages.java"] },
      { id: "dotnet-core", label: ".NET Core", aliases: [".net core", "asp.net", "aspnet", ".net", "asp.net core"], related: ["languages.csharp"] },
      { id: "entity-framework", label: "Entity Framework", aliases: ["ef", "ef core", "entity framework core", "orm"], related: ["languages.csharp"] },
      { id: "rails", label: "Ruby on Rails", aliases: ["rails", "ror"], related: ["languages.ruby"] },
      { id: "laravel", label: "Laravel", related: ["languages.php"] },
      { id: "nestjs", label: "NestJS", aliases: ["nest"], related: ["backend.nodejs", "languages.typescript"] },
    ],
  },
  {
    id: "cloud",
    label: "Cloud Platforms",
    children: [
      { id: "aws", label: "Amazon Web Services", aliases: ["aws", "amazon web services"] },
      { id: "azure", label: "Microsoft Azure", aliases: ["azure", "ms azure"] },
      { id: "gcp", label: "Google Cloud Platform", aliases: ["gcp", "google cloud"] },
      {
        id: "container-orchestration",
        label: "Container Orchestration",
        children: [
          { id: "kubernetes", label: "Kubernetes", aliases: ["k8s", "kube"] },
          { id: "docker", label: "Docker", aliases: ["containers", "docker-compose"] },
          { id: "ecs", label: "AWS ECS", aliases: ["elastic container service"] },
        ],
      },
      {
        id: "serverless",
        label: "Serverless",
        children: [
          { id: "lambda", label: "AWS Lambda", aliases: ["lambda"] },
          { id: "azure-functions", label: "Azure Functions" },
          { id: "cloud-functions", label: "Google Cloud Functions" },
        ],
      },
    ],
  },
  {
    id: "data",
    label: "Data & Databases",
    children: [
      {
        id: "relational",
        label: "Relational Databases",
        children: [
          { id: "postgresql", label: "PostgreSQL", aliases: ["postgres", "pg", "psql"] },
          { id: "mysql", label: "MySQL", aliases: ["mariadb"] },
          { id: "mssql", label: "SQL Server", aliases: ["mssql", "microsoft sql server", "sql server", "t-sql", "tsql"] },
          { id: "oracle", label: "Oracle DB", aliases: ["oracle database", "oracledb", "pl/sql", "plsql"] },
          { id: "ssis", label: "SSIS", aliases: ["sql server integration services", "ssis packages", "dtsx"] },
          { id: "ssrs", label: "SSRS", aliases: ["sql server reporting services", "ssrs reports"] },
          { id: "ssas", label: "SSAS", aliases: ["sql server analysis services", "olap"] },
        ],
      },
      {
        id: "nosql",
        label: "NoSQL Databases",
        children: [
          { id: "mongodb", label: "MongoDB", aliases: ["mongo"] },
          { id: "redis", label: "Redis" },
          { id: "dynamodb", label: "DynamoDB", aliases: ["dynamo"] },
          { id: "cassandra", label: "Cassandra", aliases: ["apache cassandra"] },
          { id: "elasticsearch", label: "Elasticsearch", aliases: ["elastic", "es", "opensearch"] },
        ],
      },
      {
        id: "big-data",
        label: "Big Data",
        children: [
          { id: "spark", label: "Apache Spark", aliases: ["pyspark", "spark"] },
          { id: "kafka", label: "Apache Kafka", aliases: ["kafka"] },
          { id: "hadoop", label: "Hadoop", aliases: ["hdfs", "mapreduce"] },
          { id: "airflow", label: "Apache Airflow", aliases: ["airflow"] },
          { id: "snowflake", label: "Snowflake" },
          { id: "databricks", label: "Databricks" },
          { id: "etl", label: "ETL", aliases: ["extract transform load", "data pipeline", "data pipelines", "elt"] },
        ],
      },
      {
        id: "analytics",
        label: "Analytics & BI",
        children: [
          { id: "power-bi", label: "Power BI", aliases: ["power bi", "powerbi", "microsoft power bi", "dax"] },
          { id: "tableau", label: "Tableau", aliases: ["tableau desktop", "tableau server", "tableau online"] },
          { id: "excel", label: "Excel", aliases: ["microsoft excel", "excel vba", "spreadsheet", "pivot tables", "vlookup"] },
          { id: "looker", label: "Looker", aliases: ["google looker", "lookml"] },
          { id: "data-visualization", label: "Data Visualization", aliases: ["data viz", "dashboards", "reporting"] },
          { id: "statistical-analysis", label: "Statistical Analysis", aliases: ["statistical analysis", "statistics", "hypothesis testing", "regression analysis"] },
        ],
      },
      {
        id: "database-skills",
        label: "Database Skills",
        children: [
          { id: "database-design", label: "Database Design", aliases: ["schema design", "data modeling", "erd", "normalization"] },
          { id: "performance-tuning", label: "Performance Tuning", aliases: ["query optimization", "database tuning", "index optimization", "execution plan"] },
          { id: "data-warehousing", label: "Data Warehousing", aliases: ["data warehouse", "dwh", "star schema", "dimensional modeling"] },
        ],
      },
    ],
  },
  {
    id: "devops",
    label: "DevOps & CI/CD",
    children: [
      { id: "terraform", label: "Terraform", aliases: ["tf", "hcl"] },
      { id: "ansible", label: "Ansible" },
      { id: "jenkins", label: "Jenkins" },
      { id: "github-actions", label: "GitHub Actions", aliases: ["gha"] },
      { id: "gitlab-ci", label: "GitLab CI/CD", aliases: ["gitlab ci"] },
      { id: "azure-devops", label: "Azure DevOps", aliases: ["ado", "azure pipelines"] },
      { id: "git", label: "Git", aliases: ["version control", "github", "gitlab", "bitbucket"] },
      { id: "linux", label: "Linux", aliases: ["ubuntu", "centos", "rhel", "debian"] },
      { id: "nginx", label: "Nginx", aliases: ["nginx"] },
      { id: "prometheus", label: "Prometheus", related: ["devops.grafana"] },
      { id: "grafana", label: "Grafana", related: ["devops.prometheus"] },
      { id: "datadog", label: "Datadog" },
    ],
  },
  {
    id: "ai-ml",
    label: "AI & Machine Learning",
    children: [
      { id: "machine-learning", label: "Machine Learning", aliases: ["ml"] },
      { id: "deep-learning", label: "Deep Learning", aliases: ["dl", "neural networks"] },
      { id: "nlp", label: "Natural Language Processing", aliases: ["nlp", "text mining"] },
      { id: "computer-vision", label: "Computer Vision", aliases: ["cv", "image recognition"] },
      { id: "tensorflow", label: "TensorFlow", aliases: ["tf-ml"] },
      { id: "pytorch", label: "PyTorch", aliases: ["torch"] },
      { id: "scikit-learn", label: "scikit-learn", aliases: ["sklearn"] },
      { id: "pandas", label: "pandas" },
      { id: "numpy", label: "NumPy", aliases: ["numpy"] },
      { id: "llm", label: "Large Language Models", aliases: ["llm", "gpt", "claude", "generative ai", "genai", "llm integration"] },
      { id: "langchain", label: "LangChain" },
      { id: "huggingface", label: "Hugging Face", aliases: ["hf", "transformers"] },
      { id: "mlops", label: "MLOps", aliases: ["ml ops", "ml operations", "model deployment", "model serving"] },
      { id: "ocr", label: "OCR", aliases: ["optical character recognition", "document intelligence", "text extraction"] },
      { id: "cognitive-services", label: "Azure Cognitive Services", aliases: ["cognitive services", "azure ai services", "azure openai"] },
    ],
  },
  {
    id: "security",
    label: "Security",
    children: [
      { id: "oauth", label: "OAuth/OIDC", aliases: ["oauth2", "openid connect", "oidc"] },
      { id: "encryption", label: "Encryption", aliases: ["aes", "rsa", "tls", "ssl"] },
      { id: "siem", label: "SIEM", aliases: ["splunk", "sentinel"] },
      { id: "penetration-testing", label: "Penetration Testing", aliases: ["pentest", "ethical hacking"] },
      { id: "iam", label: "Identity & Access Management", aliases: ["iam", "rbac", "abac"] },
      { id: "devsecops", label: "DevSecOps", aliases: ["security automation"] },
    ],
  },
  {
    id: "mobile",
    label: "Mobile Development",
    children: [
      { id: "ios", label: "iOS Development", aliases: ["ios", "iphone"], related: ["languages.swift"] },
      { id: "android", label: "Android Development", aliases: ["android"], related: ["languages.kotlin"] },
      { id: "react-native", label: "React Native", aliases: ["rn"], related: ["frontend.react"] },
      { id: "flutter", label: "Flutter", aliases: ["dart"] },
    ],
  },
  {
    id: "testing",
    label: "Testing",
    children: [
      { id: "unit-testing", label: "Unit Testing", aliases: ["jest", "mocha", "pytest", "junit", "vitest"] },
      { id: "integration-testing", label: "Integration Testing" },
      { id: "e2e-testing", label: "End-to-End Testing", aliases: ["e2e", "cypress", "playwright", "selenium"] },
      { id: "tdd", label: "Test-Driven Development", aliases: ["tdd"] },
      { id: "performance-testing", label: "Performance Testing", aliases: ["load testing", "jmeter", "k6"] },
    ],
  },
  {
    id: "methodologies",
    label: "Methodologies",
    children: [
      { id: "agile", label: "Agile", aliases: ["agile methodology"] },
      { id: "scrum", label: "Scrum", aliases: ["scrum master", "sprint"], related: ["methodologies.agile"] },
      { id: "kanban", label: "Kanban", related: ["methodologies.agile"] },
      { id: "ci-cd", label: "CI/CD", aliases: ["continuous integration", "continuous delivery", "continuous deployment"] },
      { id: "microservices", label: "Microservices Architecture", aliases: ["microservices", "service-oriented"] },
      { id: "rest-api", label: "REST API Design", aliases: ["rest", "restful", "api design", "rest api testing"] },
      { id: "graphql", label: "GraphQL", aliases: ["gql"] },
      { id: "event-driven", label: "Event-Driven Architecture", aliases: ["eda", "event sourcing", "cqrs"] },
      { id: "solution-design", label: "Solution Design", aliases: ["solution architecture", "solution design", "technical design", "system design"] },
      { id: "cloud-architecture", label: "Cloud Architecture", aliases: ["cloud architecture", "cloud design", "cloud strategy"] },
    ],
  },
  {
    id: "enterprise",
    label: "Enterprise Platforms",
    children: [
      { id: "dynamics-365", label: "Microsoft Dynamics 365", aliases: ["dynamics 365", "d365", "dynamics crm", "dynamics erp", "microsoft dynamics"] },
      { id: "power-platform", label: "Microsoft Power Platform", aliases: ["power platform", "power apps", "powerapps"] },
      { id: "power-automate", label: "Power Automate", aliases: ["power automate", "microsoft flow", "flow automation"] },
      { id: "salesforce", label: "Salesforce", aliases: ["sfdc", "salesforce crm", "apex", "lightning"] },
      { id: "sap", label: "SAP", aliases: ["sap erp", "sap hana", "s/4hana", "sap abap"] },
      { id: "servicenow", label: "ServiceNow", aliases: ["servicenow", "snow", "itsm"] },
      { id: "sharepoint", label: "SharePoint", aliases: ["sharepoint online", "spo"] },
    ],
  },
  {
    id: "pm-tools",
    label: "Project Management & Collaboration Tools",
    children: [
      { id: "jira", label: "JIRA", aliases: ["jira", "atlassian jira", "jira software", "jira service management"] },
      { id: "confluence", label: "Confluence", aliases: ["confluence", "atlassian confluence"] },
      { id: "trello", label: "Trello" },
      { id: "asana", label: "Asana" },
      { id: "monday", label: "Monday.com", aliases: ["monday"] },
      { id: "ms-project", label: "Microsoft Project", aliases: ["ms project", "mpp"] },
    ],
  },
  {
    id: "gis",
    label: "GIS & Geospatial",
    children: [
      { id: "arcgis", label: "ArcGIS", aliases: ["arcgis", "arc gis", "arcgis pro", "arcgis online", "esri", "esri arcgis"] },
      { id: "postgis", label: "PostGIS", aliases: ["postgis", "spatial sql"] },
      { id: "qgis", label: "QGIS", aliases: ["qgis"] },
      { id: "gis-general", label: "GIS", aliases: ["gis", "geographic information system", "geospatial", "spatial analysis"] },
    ],
  },
  {
    id: "ba-skills",
    label: "Business Analysis",
    children: [
      { id: "requirements-gathering", label: "Requirements Gathering", aliases: ["requirements gathering", "requirements analysis", "requirements engineering", "elicitation"] },
      { id: "user-stories", label: "User Stories", aliases: ["user stories", "acceptance criteria", "story writing"] },
      { id: "documentation", label: "Documentation", aliases: ["technical documentation", "documentation", "specs", "specification writing"] },
      { id: "stakeholder-management", label: "Stakeholder Management", aliases: ["stakeholder management", "stakeholder engagement", "client management"] },
      { id: "process-mapping", label: "Process Mapping", aliases: ["process mapping", "bpmn", "business process", "workflow design"] },
      { id: "data-analysis", label: "Data Analysis", aliases: ["data analysis", "analytical skills"] },
      { id: "test-automation", label: "Test Automation", aliases: ["test automation", "automated testing", "qa automation"] },
    ],
  },
]);
