import { buildTree } from "../builder.js";

export const technologyTree = buildTree("technology", "Technology", [
  {
    id: "languages",
    label: "Programming Languages",
    children: [
      { id: "python", label: "Python", aliases: ["py", "python3", "cpython"] },
      { id: "javascript", label: "JavaScript", aliases: ["js", "ecmascript", "es6", "es2015"] },
      { id: "typescript", label: "TypeScript", aliases: ["ts"], related: ["languages.javascript"] },
      { id: "java", label: "Java", aliases: ["jdk", "jvm"] },
      { id: "csharp", label: "C#", aliases: ["c#", "c-sharp", "dotnet", ".net"] },
      { id: "go", label: "Go", aliases: ["golang"] },
      { id: "rust", label: "Rust", aliases: ["rustlang"] },
      { id: "ruby", label: "Ruby", aliases: ["rb"] },
      { id: "php", label: "PHP" },
      { id: "swift", label: "Swift" },
      { id: "kotlin", label: "Kotlin", aliases: ["kt"], related: ["languages.java"] },
      { id: "scala", label: "Scala", related: ["languages.java"] },
      { id: "r", label: "R", aliases: ["r-lang", "rlang"] },
      { id: "sql", label: "SQL", aliases: ["structured query language"] },
      { id: "cpp", label: "C++", aliases: ["c++", "cplusplus"] },
      { id: "c", label: "C", aliases: ["clang", "ansi-c"] },
      { id: "shell", label: "Shell/Bash", aliases: ["bash", "sh", "zsh", "shell scripting"] },
      { id: "powershell", label: "PowerShell", aliases: ["pwsh", "ps1"] },
    ],
  },
  {
    id: "frontend",
    label: "Frontend Frameworks",
    children: [
      { id: "react", label: "React", aliases: ["reactjs", "react.js"], related: ["languages.javascript", "languages.typescript"] },
      { id: "angular", label: "Angular", aliases: ["angularjs", "angular.js", "ng"], related: ["languages.typescript"] },
      { id: "vue", label: "Vue.js", aliases: ["vuejs", "vue"], related: ["languages.javascript"] },
      { id: "nextjs", label: "Next.js", aliases: ["next", "nextjs"], related: ["frontend.react"] },
      { id: "svelte", label: "Svelte", aliases: ["sveltekit"] },
      { id: "html", label: "HTML", aliases: ["html5"] },
      { id: "css", label: "CSS", aliases: ["css3", "cascading style sheets"] },
      { id: "tailwind", label: "Tailwind CSS", aliases: ["tailwindcss"], related: ["frontend.css"] },
      { id: "bootstrap", label: "Bootstrap", related: ["frontend.css"] },
      { id: "sass", label: "Sass/SCSS", aliases: ["scss", "sass"], related: ["frontend.css"] },
    ],
  },
  {
    id: "backend",
    label: "Backend Frameworks",
    children: [
      { id: "nodejs", label: "Node.js", aliases: ["node", "node.js"], related: ["languages.javascript"] },
      { id: "express", label: "Express.js", aliases: ["expressjs"], related: ["backend.nodejs"] },
      { id: "fastapi", label: "FastAPI", related: ["languages.python"] },
      { id: "django", label: "Django", related: ["languages.python"] },
      { id: "flask", label: "Flask", related: ["languages.python"] },
      { id: "spring", label: "Spring Boot", aliases: ["spring", "spring-boot", "springboot"], related: ["languages.java"] },
      { id: "dotnet-core", label: ".NET Core", aliases: [".net core", "asp.net", "aspnet"], related: ["languages.csharp"] },
      { id: "rails", label: "Ruby on Rails", aliases: ["rails", "ror"], related: ["languages.ruby"] },
      { id: "laravel", label: "Laravel", related: ["languages.php"] },
      { id: "nestjs", label: "NestJS", aliases: ["nest"], related: ["backend.nodejs", "languages.typescript"] },
    ],
  },
  {
    id: "cloud",
    label: "Cloud Platforms",
    children: [
      { id: "aws", label: "Amazon Web Services", aliases: ["aws", "amazon web services"] },
      { id: "azure", label: "Microsoft Azure", aliases: ["azure", "ms azure"] },
      { id: "gcp", label: "Google Cloud Platform", aliases: ["gcp", "google cloud"] },
      {
        id: "container-orchestration",
        label: "Container Orchestration",
        children: [
          { id: "kubernetes", label: "Kubernetes", aliases: ["k8s", "kube"] },
          { id: "docker", label: "Docker", aliases: ["containers", "docker-compose"] },
          { id: "ecs", label: "AWS ECS", aliases: ["elastic container service"] },
        ],
      },
      {
        id: "serverless",
        label: "Serverless",
        children: [
          { id: "lambda", label: "AWS Lambda", aliases: ["lambda"] },
          { id: "azure-functions", label: "Azure Functions" },
          { id: "cloud-functions", label: "Google Cloud Functions" },
        ],
      },
    ],
  },
  {
    id: "data",
    label: "Data & Databases",
    children: [
      {
        id: "relational",
        label: "Relational Databases",
        children: [
          { id: "postgresql", label: "PostgreSQL", aliases: ["postgres", "pg", "psql"] },
          { id: "mysql", label: "MySQL", aliases: ["mariadb"] },
          { id: "mssql", label: "SQL Server", aliases: ["mssql", "microsoft sql server", "sql server"] },
          { id: "oracle", label: "Oracle DB", aliases: ["oracle database", "oracledb"] },
        ],
      },
      {
        id: "nosql",
        label: "NoSQL Databases",
        children: [
          { id: "mongodb", label: "MongoDB", aliases: ["mongo"] },
          { id: "redis", label: "Redis" },
          { id: "dynamodb", label: "DynamoDB", aliases: ["dynamo"] },
          { id: "cassandra", label: "Cassandra", aliases: ["apache cassandra"] },
          { id: "elasticsearch", label: "Elasticsearch", aliases: ["elastic", "es", "opensearch"] },
        ],
      },
      {
        id: "big-data",
        label: "Big Data",
        children: [
          { id: "spark", label: "Apache Spark", aliases: ["pyspark", "spark"] },
          { id: "kafka", label: "Apache Kafka", aliases: ["kafka"] },
          { id: "hadoop", label: "Hadoop", aliases: ["hdfs", "mapreduce"] },
          { id: "airflow", label: "Apache Airflow", aliases: ["airflow"] },
          { id: "snowflake", label: "Snowflake" },
          { id: "databricks", label: "Databricks" },
        ],
      },
    ],
  },
  {
    id: "devops",
    label: "DevOps & CI/CD",
    children: [
      { id: "terraform", label: "Terraform", aliases: ["tf", "hcl"] },
      { id: "ansible", label: "Ansible" },
      { id: "jenkins", label: "Jenkins" },
      { id: "github-actions", label: "GitHub Actions", aliases: ["gha"] },
      { id: "gitlab-ci", label: "GitLab CI/CD", aliases: ["gitlab ci"] },
      { id: "azure-devops", label: "Azure DevOps", aliases: ["ado", "azure pipelines"] },
      { id: "git", label: "Git", aliases: ["version control", "github", "gitlab", "bitbucket"] },
      { id: "linux", label: "Linux", aliases: ["ubuntu", "centos", "rhel", "debian"] },
      { id: "nginx", label: "Nginx", aliases: ["nginx"] },
      { id: "prometheus", label: "Prometheus", related: ["devops.grafana"] },
      { id: "grafana", label: "Grafana", related: ["devops.prometheus"] },
      { id: "datadog", label: "Datadog" },
    ],
  },
  {
    id: "ai-ml",
    label: "AI & Machine Learning",
    children: [
      { id: "machine-learning", label: "Machine Learning", aliases: ["ml"] },
      { id: "deep-learning", label: "Deep Learning", aliases: ["dl", "neural networks"] },
      { id: "nlp", label: "Natural Language Processing", aliases: ["nlp", "text mining"] },
      { id: "computer-vision", label: "Computer Vision", aliases: ["cv", "image recognition"] },
      { id: "tensorflow", label: "TensorFlow", aliases: ["tf-ml"] },
      { id: "pytorch", label: "PyTorch", aliases: ["torch"] },
      { id: "scikit-learn", label: "scikit-learn", aliases: ["sklearn"] },
      { id: "pandas", label: "pandas" },
      { id: "numpy", label: "NumPy", aliases: ["numpy"] },
      { id: "llm", label: "Large Language Models", aliases: ["llm", "gpt", "claude", "generative ai", "genai"] },
      { id: "langchain", label: "LangChain" },
      { id: "huggingface", label: "Hugging Face", aliases: ["hf", "transformers"] },
    ],
  },
  {
    id: "security",
    label: "Security",
    children: [
      { id: "oauth", label: "OAuth/OIDC", aliases: ["oauth2", "openid connect", "oidc"] },
      { id: "encryption", label: "Encryption", aliases: ["aes", "rsa", "tls", "ssl"] },
      { id: "siem", label: "SIEM", aliases: ["splunk", "sentinel"] },
      { id: "penetration-testing", label: "Penetration Testing", aliases: ["pentest", "ethical hacking"] },
      { id: "iam", label: "Identity & Access Management", aliases: ["iam", "rbac", "abac"] },
      { id: "devsecops", label: "DevSecOps", aliases: ["security automation"] },
    ],
  },
  {
    id: "mobile",
    label: "Mobile Development",
    children: [
      { id: "ios", label: "iOS Development", aliases: ["ios", "iphone"], related: ["languages.swift"] },
      { id: "android", label: "Android Development", aliases: ["android"], related: ["languages.kotlin"] },
      { id: "react-native", label: "React Native", aliases: ["rn"], related: ["frontend.react"] },
      { id: "flutter", label: "Flutter", aliases: ["dart"] },
    ],
  },
  {
    id: "testing",
    label: "Testing",
    children: [
      { id: "unit-testing", label: "Unit Testing", aliases: ["jest", "mocha", "pytest", "junit", "vitest"] },
      { id: "integration-testing", label: "Integration Testing" },
      { id: "e2e-testing", label: "End-to-End Testing", aliases: ["e2e", "cypress", "playwright", "selenium"] },
      { id: "tdd", label: "Test-Driven Development", aliases: ["tdd"] },
      { id: "performance-testing", label: "Performance Testing", aliases: ["load testing", "jmeter", "k6"] },
    ],
  },
  {
    id: "methodologies",
    label: "Methodologies",
    children: [
      { id: "agile", label: "Agile", aliases: ["agile methodology"] },
      { id: "scrum", label: "Scrum", aliases: ["scrum master", "sprint"], related: ["methodologies.agile"] },
      { id: "kanban", label: "Kanban", related: ["methodologies.agile"] },
      { id: "ci-cd", label: "CI/CD", aliases: ["continuous integration", "continuous delivery", "continuous deployment"] },
      { id: "microservices", label: "Microservices Architecture", aliases: ["microservices", "service-oriented"] },
      { id: "rest-api", label: "REST API Design", aliases: ["rest", "restful", "api design"] },
      { id: "graphql", label: "GraphQL", aliases: ["gql"] },
      { id: "event-driven", label: "Event-Driven Architecture", aliases: ["eda", "event sourcing", "cqrs"] },
    ],
  },
]);
