# Nixpacks configuration for USSP Back Office
[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = ["npm install", "cd ../platform-core && npx tsc && cd ../backoffice && npm run build"]

[start]
cmd = "npm run start"
