FROM caddy:2-alpine

COPY partners/tranzin/website/Caddyfile /etc/caddy/Caddyfile
COPY partners/tranzin/website/index.html /srv/index.html
COPY partners/tranzin/website/assets /srv/assets

EXPOSE 8080
